'use strict';

const events = {
    'GET_CATEGORIES_DATA': 'GET_CATEGORIES_DATA',
    'CATOGORIES_FETCHED':'CATOGORIES_FETCHED',
    'STATUS_CHANGED': 'STATUS_CHANGED',
    'SELECT_CATETORY': 'SELECT_CATETORY',
    'ADD_CATEGORIES': 'ADD_CATEGORIES'
};

export default events;


